version: '3.8'

services:

  rust-docker:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080'

    deploy:
      replicas: 4 
    
    restart: always

    environment:
      - PING_LISTEN_PORT=8080

    networks:
      - front-network

  proxy:

    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    ports:
      - 8080:80

    depends_on: 
      - rust-docker
    
    networks:
      - front-network

networks:
  front-network:
    driver: bridge